# Generated by Django 5.2 on 2025-04-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuariods16',
            old_name='apelido',
            new_name='endereco',
        ),
        migrations.RenameField(
            model_name='usuariods16',
            old_name='padrinho',
            new_name='escolaridade',
        ),
        migrations.RenameField(
            model_name='usuariods16',
            old_name='edv',
            new_name='idade',
        ),
        migrations.AddField(
            model_name='usuariods16',
            name='biografia',
            field=models.TextField(blank=True, default='Nasci', null=True),
        ),
        migrations.AddField(
            model_name='usuariods16',
            name='pets',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuariods16',
            name='telefone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
